<?php

/**
 * @file
 * Contains particle_cloud.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function particle_cloud_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the particle_cloud module.
    case 'help.page.particle_cloud':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Particle cloud (particle.io) integration.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function particle_cloud_theme() {
  $theme = [];

  return $theme;
}
